# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    
#services:
#  mongodb:
#   image: mongo:3.4.23
#    ports:
#      - 27017:27017
     
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Print Date
      run: date
          
    - name: Create mongoDB Docker container
      uses: DigiPie/mongo-action@v1.0.1
      
    - name: Add data to Inventory Collection
      run: mongoimport --collection=Inventory --db=BookstoreDBtest --file=inventory.json
    - name: Add data to UserColl collection
      run: mongoimport --collection=UserColl --db=BookstoreDBtest --file=usercoll.json
      
       
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    #  run: mvn compile --file pom.xml
